### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by gushmazuko**
some fix & remove nickname

### CODE REVIEW

**Comment by khashashin** [comment]
https://github.com/chechen-language/keyboards/pull/1/files#diff-e4cbe414e64bc2577440d7c093975f8048b78a9f28020bb7fc681604b3ee1cf9

Line ending differences?

**Comment by gushmazuko** [comment]
> 
```bash
❯ file chechen_latin.kvks
chechen_latin.kvks: XML 1.0 document, Unicode text, UTF-8 text, with CRLF line terminators
```

**Review by khashashin — COMMENTED** [review]
| shift & backspace width 110 | shift & backspace width none |
| --- | --- |
| image | image |

I would change the width of shift and backspace to 0 (or just leave it empty)

**Comment by gushmazuko** [comment]
> shift & backspace width 110	shift & backspace width none
> image	image
> I would change the width of shift and backspace to 0 (or just leave it empty)

This effect is only in KeyMan Redactor. Il real life keyboard resize automacily touchs.
Screenshot_select-area_20220721143201

**Comment by gushmazuko** [comment]
I did this to make the keyboard look like an iOS keyboard

**Review by khashashin — COMMENTED** [review]
There are still missing longpress additional simbols: https://github.com/chechen-language/keyboards/pull/1/files#diff-d9ccd9b7691cd411debef24d99e9ca14e9ec4247d1b67ff5075c6881ebeb127e

Would you not add them?

**Comment by khashashin** [comment]
> I did this to make the keyboard look like an iOS keyboard

If you look closely, you will notice that two buttons at the top are now wider

image

**Comment by gushmazuko** [comment]
> There are still missing longpress additional simbols: https://github.com/chechen-language/keyboards/pull/1/files#diff-d9ccd9b7691cd411debef24d99e9ca14e9ec4247d1b67ff5075c6881ebeb127e
> 
> Would you not add them?

Not finished yet

**Review by khashashin — COMMENTED** [review]
Do we also need to explicitly define the default behavior?

+ [SHIFT K_M] > 'M'
+ [SHIFT K_N] > 'N'
+ [SHIFT K_B] > 'B'
+ [SHIFT K_V] > 'V'
+ [SHIFT K_C] > 'C'
+ [SHIFT K_X] > 'X'
+ [SHIFT K_Z] > 'Z'

**Comment by gushmazuko** [comment]
> Do we also need to explicitly define the default behavior?
> 
> * [SHIFT K_M] > 'M'
> * [SHIFT K_N] > 'N'
> * [SHIFT K_B] > 'B'
> * [SHIFT K_V] > 'V'
> * [SHIFT K_C] > 'C'
> * [SHIFT K_X] > 'X'
> * [SHIFT K_Z] > 'Z'

Keyman recommends that you do this. Otherwise, in the On-Screen keyboard (virtual keyboard in PC) keys are not displayed correctly.

[It is usually best to include explicit rules to manage the output from each key](https://help.keyman.com/developer/language/guide/virtual-keys#virtual-keys-and-touch-layouts)

**Comment by khashashin** [comment]
> > Do we also need to explicitly define the default behavior?
> > 
> > * [SHIFT K_M] > 'M'
> > * [SHIFT K_N] > 'N'
> > * [SHIFT K_B] > 'B'
> > * [SHIFT K_V] > 'V'
> > * [SHIFT K_C] > 'C'
> > * [SHIFT K_X] > 'X'
> > * [SHIFT K_Z] > 'Z'
> 
> Keyman recommends that you do this. Otherwise, in the On-Screen keyboard (virtual keyboard in PC) keys are not displayed correctly.
> 
> [It is usually best to include explicit rules to manage the output from each key](https://help.keyman.com/developer/language/guide/virtual-keys#virtual-keys-and-touch-layouts)

I mean, there's nothing wrong with us doing it explicitly, but on the same URL that you shared, it says:

>Keyman maintains a mapping between the [US English](https://help.keyman.com/developer/language/guide/us-english) virtual key codes and the characters emitted by these keys. If a touch key is given one of these virtual keys (e.g. K_A), then the corresponding US English character (a) will be emitted, if no rule is provided to override that.

At the end its just more code to maintain

**Review by khashashin — APPROVED** [review]

**Pull request merged**
