### PR TITLE
Feat/auto caps and shift caps layer

### PR DESCRIPTION
**Pull request by gushmazuko**

### CODE REVIEW

**Comment by khashashin** [comment]
Some buttons are not correct, they output different characters. I think we need to test them all

image

**Comment by gushmazuko** [comment]
> Some buttons are not correct, they output different characters. I think we need to test them all
> 
> image

It's because we are defined the `K_QUOTE` equal to `ç`.
For symbols touchs we need to hardcode Unicode values.

Screenshot_1

Screenshot_2

**Comment by khashashin** [comment]
@gushmazuko I tested it with hardcoded Unicode values of type "U_blabla", but I had the same problems. Did you test it with hardcoded values?

**Comment by khashashin** [comment]
> @gushmazuko I tested it with hardcoded Unicode values of type "U_blabla", but I had the same problems. Did you test it with hardcoded values?

I just tested your PR and it works correctly 👍

**Comment by khashashin** [comment]
Could you check my latest update, what do you think of this update? I changed the behavior of switching back to the default level of two levels - altgr & altgr shift

**Comment by gushmazuko** [comment]
> Could you check my latest update, what do you think of this update? I changed the behavior of switching back to the default level of two levels - altgr & altgr shift

Ambiguous decision, both options need to be tested. What do you think of `AltGr Lock` (like `Caps Lock`)?

**Comment by gushmazuko** [comment]
There are an issue on last update (https://github.com/chechen-language/keyboards/pull/3/commits/8801b9f07b576af58b333368bf55bd2e64762587):
layer `rightalt-shift` work like `rightalt-caps`, although it should exit to `rightalt` after keystroke.

**Comment by khashashin** [comment]
> > Could you check my latest update, what do you think of this update? I changed the behavior of switching back to the default level of two levels - altgr & altgr shift
> 
> Ambiguous decision, both options need to be tested. What do you think of `AltGr Lock` (like `Caps Lock`)?

Just try to type "ṫäẋẋara" or even better "ṪÄẊẊARA" you will notice the issue immediately. It takes so much unnecessary clicks

**Comment by gushmazuko** [comment]
The [problem ](https://github.com/chechen-language/keyboards/pull/3#issuecomment-1193103087)I wrote above is still there, my commit didn't work. I reversed the change.

**Comment by khashashin** [comment]
I like this change https://github.com/chechen-language/keyboards/pull/3/commits/ede01cc65e27c416b27412665bf2c2bdd39c66c7 well done 👍

**Review by khashashin — APPROVED** [review]

**Comment by khashashin** [comment]
can we merge that? Let's open new PR to fix missing ";" and "'"

**Pull request merged**
